### ISSUE TITLE
Can you please put it on nuget?

### ISSUE THREAD

**Issue by stanislavromanov** [mikeckennedy/mongodb-query-helper-for-dotnet#1]

**Comment by mikeckennedy** [comment]
Hi Steve,

That is something I have been thinking about doing. I'm pretty busy right now but I will add it soon.

Thanks!

**Comment by Continuity-Joe** [comment]
+1

**Comment by mikeckennedy** [comment]
Thanks guys. Maybe next week I can get to it? I'm traveling on work this until Friday.

**Comment by stanislavromanov** [comment]
Okey man, It shouldn't be that hard, I think.

**Comment by mikeckennedy** [comment]
nope, super easy. just really busy with the day job!

**Comment by mikeckennedy** [comment]
Finally got this NuGet. Thank you guys: https://www.nuget.org/packages/MongoDB.QueryHelper
